project_name: podtato

before:
  hooks:
    - go mod tidy

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}.{{ .Os }}-{{ .Arch }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/dirien/podtato-head-naml/cmd/version.Version={{.Version}}
      - -s -w -X github.com/dirien/podtato-head-naml/cmd/version.Revision={{.Commit}}
      - -s -w -X github.com/dirien/podtato-head-naml/cmd/version.Branch={{.Branch}}
      - -s -w -X github.com/dirien/podtato-head-naml/cmd/version.BuildUser=goreleaser
      - -s -w -X github.com/dirien/podtato-head-naml/cmd/version.BuildDate={{.Date}}
